// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl4_oPflgyE42VhsKMTMCcQpNWaQg6nJE',
    appId: '1:953780714962:web:93c665a9f359c9c5f95c0b',
    messagingSenderId: '953780714962',
    projectId: 'heitor-e-jessica',
    authDomain: 'heitor-e-jessica.firebaseapp.com',
    storageBucket: 'heitor-e-jessica.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtHEDIiwJl-_K4iM0F5wIXKOshEqacRYA',
    appId: '1:953780714962:android:299f632c70b177b8f95c0b',
    messagingSenderId: '953780714962',
    projectId: 'heitor-e-jessica',
    storageBucket: 'heitor-e-jessica.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe3xgs8vTYMbiRuEPS84gjQtYGkcDOzvk',
    appId: '1:953780714962:ios:956ba41f8fab94e2f95c0b',
    messagingSenderId: '953780714962',
    projectId: 'heitor-e-jessica',
    storageBucket: 'heitor-e-jessica.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe3xgs8vTYMbiRuEPS84gjQtYGkcDOzvk',
    appId: '1:953780714962:ios:956ba41f8fab94e2f95c0b',
    messagingSenderId: '953780714962',
    projectId: 'heitor-e-jessica',
    storageBucket: 'heitor-e-jessica.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl4_oPflgyE42VhsKMTMCcQpNWaQg6nJE',
    appId: '1:953780714962:web:9ac450ae988e4fd5f95c0b',
    messagingSenderId: '953780714962',
    projectId: 'heitor-e-jessica',
    authDomain: 'heitor-e-jessica.firebaseapp.com',
    storageBucket: 'heitor-e-jessica.firebasestorage.app',
  );

}